application: firiplanning
version: production
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin
- url: /workers/.*
  script: workers.py
  login: admin
- url: /.*
  login: required
  script: main.py
